version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  browser-tools: circleci/browser-tools@1.1
  orbs:
  bullet_train_testing: gazayas/bullet_train_testing@dev:070cfad11b6c9a58900353dfc9e57f6ce60ce7bd
aliases:
  - &restore_bundler_cache
      name: Restore Bundler cache
      keys:
        - gem-cache-v1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        - gem-cache-v1-{{ .Branch }}-
        - gem-cache-v1-
  - &restore_yarn_cache
      name: Restore Yarn cache
      keys:
        - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - yarn-packages-v1-{{ .Branch }}-
        - yarn-packages-
  - &save_bundle_cache
      name: Save Bundle cache
      key: gem-cache-v1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle
  - &save_yarn_cache
      name: Save Yarn cache
      key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      paths:
        - node_modules
  - &ruby_node_browsers_docker_image
      - image: cimg/ruby:3.1.2-browsers
        environment:
          PGHOST: localhost
          PGUSER: untitled_application
          RAILS_ENV: test
  - &postgres_docker_image
      - image: circleci/postgres
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: untitled_application_test
          POSTGRES_USER: untitled_application
  - &wait_for_docker
      # We run this because the DB might not be available for a while due to a race condition.
      run: dockerize -wait tcp://localhost:5432 -timeout 1m
jobs:
  'Local Minitest':
    docker:
      - <<: *ruby_node_browsers_docker_image
      - <<: *postgres_docker_image
      - image: circleci/redis
    executor: ruby/default
    steps:
      - browser-tools/install-browser-tools
      - checkout

      # Install dependencies
      - run: "bundle install"
      - run: "bundle clean --force"
      - run: "yarn install"
      - *wait_for_docker
      - run:
          name: Run unit tests
          command: bundle exec rails test

  'Local Standard Ruby':
    docker:
      - <<: *ruby_node_browsers_docker_image
    steps:
      - checkout

      # TODO Figure out how to make these work for `tmp/starter`
      # # Restore dependency caches
      # - restore_cache: *restore_bundler_cache
      # - restore_cache: *restore_yarn_cache

      # Install dependencies
      - ruby/bundle-install
      - run: bundle clean --force
      - run: yarn install

      # # Save dependency caches
      # # We only do this as part of this job, because it's time consuming and we don't want it to slow down test runners.
      # - save_cache: *save_bundle_cache
      # - save_cache: *save_yarn_cache

      - bullet_train_testing/standard_ruby

  'Starter Repo Minitest':
    docker:
      - <<: *ruby_node_browsers_docker_image
      - <<: *postgres_docker_image
      - image: circleci/redis
    executor: ruby/default
    parallelism: 16
    steps:
      - browser-tools/install-browser-tools
      - checkout

      # TODO Figure out how to make these work for `tmp/starter`
      # - restore_cache: *restore_bundler_cache
      # - restore_cache: *restore_yarn_cache

      - *wait_for_docker

      - bullet_train_testing/starter_repo_minitest:
          packageName: bullet_train-themes-light
          knapsackPro: false

      # If you want to gather test results in CircleCI when not running tests in parallel,
      # include `minitest-ci` in your Gemfile and uncomment the following step.
      # You can access the test results via the "Tests" tab within each build in CircleCI.
      #
      # - store_test_results:
      #     path: test/reports

  'Starter Repo Minitest for Super Scaffolding':
    docker:
      - <<: *ruby_node_browsers_docker_image
      - <<: *postgres_docker_image
      - image: circleci/redis
    executor: ruby/default
    parallelism: 16
    steps:
      - browser-tools/install-browser-tools
      - checkout

      # TODO Figure out how to make these work for `tmp/starter`
      # # Restore dependency caches
      # - restore_cache: *restore_bundler_cache
      # - restore_cache: *restore_yarn_cache

      - *wait_for_docker

      - bullet_train_testing/starter_repo_super_scaffolding:
          packageName: bullet_train-themes-light
          knapsackPro: false

workflows:
  version: 2
  build:
    jobs:
      # TODO Figure out why this isn't passing.
      # - 'Local Minitest'
      - 'Local Standard Ruby'
      - 'Starter Repo Minitest'
      - 'Starter Repo Minitest for Super Scaffolding'
